Allow activating first version of virtualenv even if there are multiple versions in pyenv (#105)

diff --git a/bin/pyenv-sh-activate b/bin/pyenv-sh-activate
--- a/bin/pyenv-sh-activate
+++ b/bin/pyenv-sh-activate
@@ -14,6 +14,7 @@
 set -e
 [ -n "$PYENV_DEBUG" ] && set -x
 
+unset DEACTIVATE
 unset QUIET
 unset VERBOSE
 
@@ -23,6 +24,9 @@ while [ $# -gt 0 ]; do
     # Provide pyenv completions
     echo --unset
     exec pyenv-virtualenvs --bare
+    ;;
+  "--deactivate" )
+    DEACTIVATE=1
     ;;
   "--no-error" | "--quiet" )
     QUIET=1
@@ -56,30 +60,40 @@ if [ -z "${PYENV_VIRTUALENV_INIT}" ]; then
   no_shell=
 fi
 
-if [ "${#versions[@]}" -gt 1 ]; then
-  [ -n "$QUIET" ] || echo "pyenv-virtualenv: cannot activate multiple versions at once: ${versions[@]}" 1>&2
+venv="${versions}"
+
+if ! pyenv-virtualenv-prefix "${venv}" 1>/dev/null 2>&1; then
+  if [ -z "$QUIET" ]; then
+    echo "pyenv-virtualenv: version \`${venv}' is not a virtualenv" 1>&2
+  fi
   echo "false"
   exit 1
 fi
 
-if pyenv-prefix "${versions}" 1>/dev/null 2>&1; then
-  if ! pyenv-virtualenv-prefix "${versions}" 1>/dev/null 2>&1; then
-    [ -n "$QUIET" ] || echo "pyenv-virtualenv: version \`${versions}' is not a virtualenv" 1>&2
-    echo "false"
-    exit 1
+# exit as error if there are multiple virtualenvs
+# https://github.com/yyuu/pyenv-virtualenv/issues/105
+for version in "${versions[@]}"; do
+  if [[ "${version}" != "${venv}" ]]; then
+    if pyenv-virtualenv-prefix "${version}" 1>/dev/null 2>&1; then
+      if [ -z "$QUIET" ]; then
+        echo "pyenv-virtualenv: cannot activate multiple versions at once: ${versions[@]}" 1>&2
+      fi
+      echo "false"
+      exit 1
+    fi
   fi
-else
-  version="$(pyenv-version-name)"
-  versions="${version%/envs/*}/envs/${versions}"
-  if ! pyenv-virtualenv-prefix "${versions}" 1>/dev/null 2>&1; then
-    [ -n "$QUIET" ] || echo "pyenv-virtualenv: version \`${versions}' is not an environment of anaconda/miniconda" 1>&2
-    echo "false"
-    exit 1
-  fi
-fi
+done
 
 shell="${PYENV_SHELL:-${SHELL##*/}}"
-prefix="$(pyenv-prefix "${versions}")"
+prefix="$(pyenv-prefix "${venv}")"
+
+if [[ "${VIRTUAL_ENV}" == "${prefix}" ]]; then
+  if [ -z "${QUIET}" ]; then
+    echo "pyenv-virtualenv: version \`${venv}' is already activated" 1>&2
+  fi
+  echo "true"
+  exit 0
+fi
 
 # Display setup instruction, if pyenv-virtualenv has not been initialized.
 # if 'pyenv virtualenv-init -' is not found in "$profile"
@@ -87,36 +101,33 @@ if [ -z "$PYENV_VIRTUALENV_INIT" ]; then
   pyenv-virtualenv-init >&2 || true
 fi
 
-echo "pyenv-virtualenv: activate ${versions}" 1>&2
-
-if [ -z "$no_shell" ]; then
-  echo "pyenv shell \"${versions}\";"
-  # shell version set in pyenv-sh-activate should be unset
-  # https://github.com/yyuu/pyenv-virtualenv/issues/61
-  case "$shell" in
-  fish )
-    echo "setenv PYENV_ACTIVATE_SHELL 1;"
-    ;;
-  * )
-    echo "export PYENV_ACTIVATE_SHELL=1;"
-    ;;
-  esac
+if [ -n "${DEACTIVATE}" ]; then
+  pyenv-sh-deactivate ${QUIET+--quiet} ${VERBOSE+--verbose}
 fi
 
-case "${shell}" in
-fish )
-  cat <<EOS
-set -e PYENV_DEACTIVATE;
-setenv PYENV_ACTIVATE "${prefix}";
+echo "pyenv-virtualenv: activate ${venv}" 1>&2
+
+if [ -z "$no_shell" ]; then
+  # shell version set in pyenv-sh-activate should be unset
+  # https://github.com/yyuu/pyenv-virtualenv/issues/61
+  OLDIFS="$IFS"
+  IFS=:
+  case "$shell" in
+  fish )
+    cat <<EOS
+setenv PYENV_VERSION "${versions[*]}";
+setenv PYENV_ACTIVATE_SHELL 1;
 EOS
-  ;;
-* )
-  cat <<EOS
-unset PYENV_DEACTIVATE;
-export PYENV_ACTIVATE="${prefix}";
+    ;;
+  * )
+    cat <<EOS
+export PYENV_VERSION="${versions[*]}";
+export PYENV_ACTIVATE_SHELL=1;
 EOS
-  ;;
-esac
+    ;;
+  esac
+  IFS="$OLDIFS"
+fi
 
 # virtualenv/pyvenv
 case "${shell}" in
@@ -130,8 +141,8 @@ esac
 
 # anaconda/miniconda
 if [ -x "${prefix}/bin/conda" ]; then
-  if [[ "${versions}" != "${versions%/envs/*}" ]]; then
-    CONDA_DEFAULT_ENV="${versions##*/envs/}"
+  if [[ "${venv}" != "${venv%/envs/*}" ]]; then
+    CONDA_DEFAULT_ENV="${venv##*/envs/}"
   else
     CONDA_DEFAULT_ENV="root"
   fi
